apiVersion: apps/v1
kind: Deployment
metadata:
  name: 4eyes
  labels:
    app: 4eyes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 4eyes
  template:
    metadata:
      labels:
        app: 4eyes
    spec:
      containers:
        - name: 4eyes
          image: explabs/4eyes
          env:
          - name: AUTH_TYPE
            value: dex
          - name: OIDC_URL
            value: https://dex.local
          - name: OIDC_PREFIX
            value: "oidc:"
          - name: OIDC_CLIENT_ID
            value: oauth2-proxy
          - name: ETCD_ENDPOINT
            value: etcd:2379
---
kind: Service
apiVersion: v1
metadata:
  name: eyes
spec:
  selector:
    app: 4eyes
  ports:
    - port: 9443
      name: http

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 4eyes
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
    nginx.ingress.kubernetes.io/auth-signin: https://auth.dev.local/oauth2/start
    nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy.oauth2-proxy.svc.cluster.local/oauth2/auth
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/auth-response-headers: "Authorization, X-Auth-Request-Email, X-Auth-Request-User, X-Forwarded-Access-Token, X-Auth-Request-Access-Token"

spec:
  ingressClassName: nginx
  rules:
  - host: web.dev.local
    http:
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: eyes
              port: 
                name: http
  tls:
    - hosts:
        - web.dev.local
      secretName: web-tls

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 4eyes-webhook
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer

spec:
  ingressClassName: nginx
  rules:
  - host: web.dev.local
    http:
      paths:
        - path: /authorize
          pathType: ImplementationSpecific
          backend:
            service:
              name: eyes
              port: 
                name: http
  tls:
    - hosts:
        - web.dev.local
      secretName: web-tls